# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae840ec5661f22138472950d462d3658543723f85065325cd485a3ba03834d9a38f333c6de60b385f9bd6f0a0722251f23e3a1824cc8bd266cb51855d3a5b72a
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: ballast-systems.herokuapp.com
  owner_email: <%= ENV["OWNER_EMAIL"] %>

test:
  secret_key_base: 27b312b20f9b83aa1ba188eb7a8cf960a6708f467cf9a542d2faa7db09ec786fe00d569df689611285e51b2908c3dd28a9ebe715002b8287e26eb55675a4ad67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: ballast-systems.herokuapp.com
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
